### ISSUE TITLE
不是issue ，是一个小建议，就是 cachekey 的拼接方式 ":"  ，看看有可能让用户自定义不？ 

### ISSUE THREAD

**Issue by ys-d** [mgtv-tech/jetcache-go#39]
![image](https://github.com/user-attachments/assets/eb0f14f3-d9bc-4299-b51f-bd9fef8c48dc)

如果redis 已经有很多缓存key，然后拼接方式 不是  “：”  ，这里就非常难办了

**Comment by ys-d** [comment]
最好去掉分隔符

**Comment by daoshenzzg** [comment]
可以的。Cache Options 加一个可选项，默认 cache key 的分隔符为":"，这样就可以自定义啦。

**Comment by x1nchen** [comment]
我这边最近集成到项目里的时候也有类似的问题。不过因为我是新业务，可以允许不同的 key 的分隔符的风格。能自定义是最好的

**Comment by tollcc** [comment]
Cache Option中已增加2个可选参数separatorDisabled和separator，separatorDisabled可禁用分隔符，separator可自定义分隔符，可根据自己需要灵活配置使用

**Comment by ys-d** [comment]
大佬，如果只用本地缓存和兜底函数，不要redis 缓存这一层，是可以通过什么控制呀

**Comment by daoshenzzg** [comment]
> 大佬，如果只用本地缓存和兜底函数，不要redis 缓存这一层，是可以通过什么控制呀

可以参考下这个哈：https://github.com/mgtv-tech/jetcache-go/blob/main/cache_test.go#L866-L891
